export const userEndpoints = {
  SIGNUP: "/register",
  SIGNIN: "login",
  VERIFY_OTP: "/verify-otp",
  FETCHDOCTORS : "/get-doctors",
  // REFRESH_TOKEN : "/refreshToken"
  LOGOUT : "/logout",
  REFRESH_RESPONSE:"/refreshToken",
  FETCH_SPECIALIZATION : '/specialization',
  APPOINTMENTS: `/appointments`,
  BOOK_APPOINTMENT:'/book-appointment',
  CREATE_PAYPAL_ORDER:'/create-paypal-order',
  CAPTURE_PAYPAL_ORDER:'/capture-paypal-order',
  FETCH_APPOINTMENTS:(userId:string)=> `appointments/${userId}`,
  FETCH_DOCTOR_PROFILE:(doctorId:string)=>`/doctor/${doctorId}`,
  FETCH_DOCTOR_BY_SPECIALIZATION:(specializationId:string)=>`/doctor/specialization/${specializationId}`,
  POST_REVIEW_RATING:`/review-rating`,
  FETCH_DOCTOR_REVIEW:(doctorId:string)=>`/reviews/${doctorId}`,
  EDIT_REVIEW_AND_RATING:(reviewId:string)=>`/review/${reviewId}`,
  GET_OR_CREATE_ROOM:'/chat/room',
  GET_MESSAGES:(roomId:string)=>`/chat/messages/${roomId}`,
  SEND_MESSAGE:'/chat/message'
};

export const doctorEndpoints = {
  SIGNUP: "/register",
  SIGNIN: "/login",
  VERIFY_OTP: "/verifyOtp",
  VERIFICATION_SECITON_ONE: "/verification/step1",
  VERIFICATION_SECTION_TWO: "/verification/step2",
  DOCTOR_STATUS : (email:string)=> `/status/${email}`,
  GOOGLE_LOGIN:'/doctor-google-login', 
  GET_DOCTOR_PROFILE:(doctorId:string)=>`/profile/${doctorId}`,
  LOGOUT:'/logout',
  ADD_SLOTS : '/add-slot',
  REFRESH_RESPONSE:"/refreshToken",
  EDIT_DOCTOR_PROFILE : (doctorId:string)=>`/profile/editProfile/${doctorId}`,
  SPECIALITIES : '/get-all-specialities',
  APPOINTMENTS:(doctorId:string)=>`/appointments?doctorId=${doctorId}`,
  DELETESLOT:(slotId:string)=>`/deleteSlot/${slotId}`,
  FETCH_ALL_APPOINTMENTS:(doctorId:string)=>`/appointments/${doctorId}`,
  UPDATE_APPOINTMENT_STATUS :(appointmentId:string)=> `/update-status/${appointmentId}`,
  FETCH_REVIEW_AND_RATING : (doctorId:string)=> `/review/${doctorId}`
};

export const adminEndpoints = {
  SIGNIN: "/login",
  PATIENTS: "/all-patients",
  SPECIALITIES: "/specialities",
  ADD_SPECIALITIES: "/add-speciality",
  UPDATE_SPECIALITIES : (id:string)=>`/update-speciality/${id}`,
  DELETE_SPECIALITIES : (id:string)=> `/delete-speciality/${id}`,
  RESTORE_SPECIALITIES : (id:string)=> `/restore-speciality/${id}`,
  FETCH_SPECIALITIES : (id:string)=> `/specialities/${id}`,
  ACTIVE_SPECIALITIES: "/active-specialities",
  DOCTORS: "/doctors",
  DOCTOR_BY_ID: (doctorId: string) => `/doctors/${doctorId}`,
  APPROVE_DOCTOR : (doctorId:string)=> `/doctors/approve-doctor/${doctorId}`,
  BLOCK_USER : (userId:string)=> `/all-patients/block/${userId}`,
  UNBLOCK_USER: (userId: string) => `/all-patients/unblock/${userId}`,
  FETCH_DOCTOR_APPOINTMENTS:"/appointments",
  BLOCK_UNBLOCK_DOCTOR:(doctorId:string)=> `/doctors/block/${doctorId}`,
  REFRESH_RESPONSE:"/refreshToken",
  APPOINTMENT_FILTER_BY_DATE : (slotDate:string,doctorId:string)=>`/appointments/filter?slotDate=${slotDate}&doctorId=${doctorId}`,
  FETCH_DOCTOR_REVIEW:(doctorId:string)=>`/review/${doctorId}`
};
